"""Compliance audit report generator.

Produces a self-contained HTML (and optionally PDF) report explaining why a
specific wallet received a given risk score on a particular date. Designed
for regulators and exchange compliance teams responding to audit inquiries.
"""

import logging
import os
from datetime import datetime
from typing import Optional

from pydantic import BaseModel

logger = logging.getLogger("ledgerlens.compliance_report")

REPORT_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>LedgerLens Compliance Report — {{ wallet }}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         max-width: 900px; margin: 40px auto; padding: 0 20px; color: #1a1a1a; }
  h1 { color: #0a2540; border-bottom: 3px solid #0a2540; padding-bottom: 10px; }
  h2 { color: #1a3a5c; margin-top: 30px; }
  .meta { color: #666; font-size: 0.9em; }
  .score-box { background: #f8f9fa; border-left: 4px solid {{ score_color }};
               padding: 15px 20px; margin: 20px 0; border-radius: 4px; }
  .score-value { font-size: 2em; font-weight: bold; color: {{ score_color }}; }
  table { border-collapse: collapse; width: 100%; margin: 15px 0; }
  th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
  th { background: #f0f2f5; }
  .bar { background: #3b82f6; height: 16px; border-radius: 3px; }
  .bar-neg { background: #ef4444; }
  .footer { margin-top: 40px; padding-top: 15px; border-top: 1px solid #ddd;
            font-size: 0.85em; color: #888; }
  @media print { body { margin: 0; } }
</style>
</head>
<body>

<h1>LedgerLens Compliance Audit Report</h1>
<p class="meta">
  <strong>Wallet:</strong> {{ wallet }}<br>
  <strong>Report Date:</strong> {{ report_date }}<br>
  <strong>Scoring Date:</strong> {{ scoring_date }}<br>
  <strong>Generated:</strong> {{ generated_at }}
</p>

<h2>Executive Summary</h2>
<div class="score-box">
  <div class="score-value">Risk Score: {{ score }} / 100</div>
  <p>Confidence: {{ confidence }}%
  {% if ci_low is not none and ci_high is not none %}
    (95%% CI: {{ ci_low }} – {{ ci_high }})
  {% endif %}
  </p>
  <p>{{ risk_level }} risk. {{ summary_text }}</p>
</div>

<h2>Top Contributing Features (SHAP Attribution)</h2>
<table>
  <thead><tr><th>#</th><th>Feature</th><th>Value</th><th>SHAP Impact</th><th>Description</th></tr></thead>
  <tbody>
  {% for i, feat in enumerate(top_features) %}
  <tr>
    <td>{{ i + 1 }}</td>
    <td><code>{{ feat.name }}</code></td>
    <td>{{ feat.value }}</td>
    <td>
      <div class="bar{{ ' bar-neg' if feat.shap < 0 else '' }}"
           style="width: {{ feat.bar_width }}px"></div>
      {{ feat.shap_display }}
    </td>
    <td>{{ feat.description }}</td>
  </tr>
  {% endfor %}
  </tbody>
</table>

<h2>Benford's Law Analysis</h2>
<table>
  <thead><tr><th>Metric</th><th>Value</th></tr></thead>
  <tbody>
  <tr><td>Chi-squared statistic</td><td>{{ benford.chi2 }}</td></tr>
  <tr><td>Mean Absolute Deviation</td><td>{{ benford.mad }}</td></tr>
  <tr><td>Benford flag</td><td>{{ benford.flag }}</td></tr>
  </tbody>
</table>

<h2>Trade Timeline</h2>
<p>Total trades in scoring window: {{ trade_count }}</p>
{% if trades %}
<table>
  <thead><tr><th>Time</th><th>Pair</th><th>Amount</th><th>Price</th><th>Type</th></tr></thead>
  <tbody>
  {% for t in trades[:20] %}
  <tr>
    <td>{{ t.time }}</td>
    <td>{{ t.pair }}</td>
    <td>{{ t.amount }}</td>
    <td>{{ t.price }}</td>
    <td>{{ t.trade_type }}</td>
  </tr>
  {% endfor %}
  {% if trade_count > 20 %}
  <tr><td colspan="5"><em>... and {{ trade_count - 20 }} more trades</em></td></tr>
  {% endif %}
  </tbody>
</table>
{% endif %}

<h2>Model Provenance</h2>
<table>
  <thead><tr><th>Field</th><th>Value</th></tr></thead>
  <tbody>
  <tr><td>Model version</td><td>{{ model_version }}</td></tr>
  <tr><td>Training date</td><td>{{ training_date }}</td></tr>
  <tr><td>Ensemble members</td><td>{{ ensemble_members }}</td></tr>
  </tbody>
</table>

<h2>Data Provenance</h2>
<table>
  <thead><tr><th>Field</th><th>Value</th></tr></thead>
  <tbody>
  <tr><td>Network</td><td>{{ network }}</td></tr>
  <tr><td>Horizon cursor range</td><td>{{ cursor_start }} — {{ cursor_end }}</td></tr>
  <tr><td>Data source</td><td>Stellar Horizon API</td></tr>
  </tbody>
</table>

<div class="footer">
  <p>This report was generated by LedgerLens v{{ app_version }}. It is read-only
  and deterministic: the same wallet + date inputs will always produce the same
  output. Report ID: {{ report_id }}</p>
</div>

</body>
</html>
"""


class FeatureAttribution(BaseModel):
    name: str
    value: float
    shap: float
    shap_display: str
    bar_width: int
    description: str


class BenfordSummary(BaseModel):
    chi2: str
    mad: str
    flag: str


class TradeSummary(BaseModel):
    time: str
    pair: str
    amount: str
    price: str
    trade_type: str


class ComplianceReportData(BaseModel):
    wallet: str
    report_date: str
    scoring_date: str
    generated_at: str
    score: int
    confidence: int
    ci_low: Optional[int] = None
    ci_high: Optional[int] = None
    risk_level: str
    summary_text: str
    score_color: str
    top_features: list[FeatureAttribution]
    benford: BenfordSummary
    trade_count: int
    trades: list[TradeSummary]
    model_version: str
    training_date: str
    ensemble_members: str
    network: str
    cursor_start: str
    cursor_end: str
    app_version: str
    report_id: str


FEATURE_DESCRIPTIONS = {
    "trade_count": "Total number of trades in the scoring window",
    "unique_counterparties": "Number of distinct trading counterparties",
    "avg_trade_amount": "Mean trade amount in XLM equivalent",
    "self_trade_ratio": "Fraction of trades where base and counter accounts match",
    "round_trip_ratio": "Fraction of trades that form round-trip patterns",
    "temporal_concentration": "How concentrated trades are in time (entropy)",
    "counterparty_concentration": "Gini coefficient of counterparty volume distribution",
    "benford_mad": "Mean absolute deviation from Benford's Law digit distribution",
    "price_volatility": "Standard deviation of price changes across trades",
    "volume_velocity": "Rate of volume increase over the scoring window",
}


def _risk_level(score: int) -> str:
    if score >= 80:
        return "High"
    if score >= 50:
        return "Medium"
    return "Low"


def _score_color(score: int) -> str:
    if score >= 80:
        return "#dc2626"
    if score >= 50:
        return "#f59e0b"
    return "#16a34a"


def _summary_text(score: int) -> str:
    if score >= 80:
        return ("This wallet exhibits strong indicators of wash trading or market "
                "manipulation and warrants further investigation.")
    if score >= 50:
        return ("This wallet shows some anomalous trading patterns that may warrant "
                "monitoring or further analysis.")
    return ("This wallet's trading patterns fall within normal ranges. No immediate "
            "action is recommended.")


def generate_report_data(
    wallet: str,
    date: str,
    score_record: Optional[dict] = None,
    feature_vector: Optional[dict] = None,
    shap_values: Optional[dict] = None,
    benford_metrics: Optional[dict] = None,
    trades: Optional[list] = None,
    model_metadata: Optional[dict] = None,
) -> ComplianceReportData:
    """Build the report data model from scoring artifacts."""
    import hashlib

    score = score_record.get("score", 0) if score_record else 0
    confidence = score_record.get("confidence", 0) if score_record else 0
    ci_low = score_record.get("ci_low") if score_record else None
    ci_high = score_record.get("ci_high") if score_record else None

    top_features = []
    if shap_values and feature_vector:
        sorted_feats = sorted(shap_values.items(), key=lambda x: abs(x[1]), reverse=True)[:5]
        max_abs = max(abs(v) for _, v in sorted_feats) if sorted_feats else 1.0
        for name, shap_val in sorted_feats:
            top_features.append(FeatureAttribution(
                name=name,
                value=round(feature_vector.get(name, 0.0), 4),
                shap=round(shap_val, 4),
                shap_display=f"{shap_val:+.4f}",
                bar_width=max(5, int(abs(shap_val) / max_abs * 150)),
                description=FEATURE_DESCRIPTIONS.get(name, ""),
            ))

    benford = BenfordSummary(
        chi2=f"{benford_metrics.get('chi2', 0.0):.3f}" if benford_metrics else "N/A",
        mad=f"{benford_metrics.get('mad', 0.0):.4f}" if benford_metrics else "N/A",
        flag=str(benford_metrics.get("flag", "N/A")) if benford_metrics else "N/A",
    )

    trade_summaries = []
    if trades:
        for t in trades[:20]:
            trade_summaries.append(TradeSummary(
                time=str(t.get("ledger_close_time", "")),
                pair=f"{t.get('base_asset', '?')}/{t.get('counter_asset', '?')}",
                amount=f"{t.get('base_amount', 0.0):.4f}",
                price=f"{t.get('price', 0.0):.6f}",
                trade_type=t.get("trade_type", "orderbook"),
            ))

    model_version = (model_metadata or {}).get("version", "unknown")
    training_date = (model_metadata or {}).get("training_date", "unknown")
    ensemble_members = (model_metadata or {}).get("ensemble_members", "RF, XGBoost, LightGBM")

    report_id = hashlib.sha256(f"{wallet}:{date}".encode()).hexdigest()[:16]

    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    return ComplianceReportData(
        wallet=wallet,
        report_date=date,
        scoring_date=date,
        generated_at=now,
        score=score,
        confidence=confidence,
        ci_low=ci_low,
        ci_high=ci_high,
        risk_level=_risk_level(score),
        summary_text=_summary_text(score),
        score_color=_score_color(score),
        top_features=top_features,
        benford=benford,
        trade_count=len(trades) if trades else 0,
        trades=trade_summaries,
        model_version=model_version,
        training_date=training_date,
        ensemble_members=ensemble_members,
        network=os.getenv("NETWORK", "testnet"),
        cursor_start=(score_record or {}).get("cursor_start", "N/A"),
        cursor_end=(score_record or {}).get("cursor_end", "N/A"),
        app_version="0.1.0",
        report_id=report_id,
    )


def render_html(data: ComplianceReportData) -> str:
    """Render the report data into a self-contained HTML string."""
    try:
        from jinja2 import Environment
        env = Environment(autoescape=True)
        template = env.from_string(REPORT_TEMPLATE)
        return template.render(**data.model_dump(), enumerate=enumerate)
    except ImportError:
        return _render_html_simple(data)


def _render_html_simple(data: ComplianceReportData) -> str:
    """Fallback renderer when Jinja2 is not installed."""
    d = data.model_dump()
    html = REPORT_TEMPLATE
    for key, val in d.items():
        if isinstance(val, str):
            html = html.replace("{{ " + key + " }}", val)
        elif isinstance(val, (int, float)):
            html = html.replace("{{ " + key + " }}", str(val))
    return html


def render_pdf(html: str, output_path: str) -> str:
    """Render HTML to PDF using weasyprint. Returns the output path."""
    from weasyprint import HTML
    HTML(string=html).write_pdf(output_path)
    return output_path


class ComplianceReportGenerator:
    """High-level report generator for compliance audit reports."""

    def generate(
        self,
        wallet: str,
        date: str,
        output_path: str,
        fmt: str = "html",
    ) -> str:
        """Generate a compliance report and write it to output_path."""
        from detection.storage import (
            get_feature_vector_for_wallet,
            get_shap_values,
        )

        score_record = self._load_score(wallet, date)
        feature_vector = get_feature_vector_for_wallet(wallet)
        shap_vals = get_shap_values(wallet)
        benford_metrics = self._load_benford(wallet)
        trades = self._load_trades(wallet, date)
        model_metadata = self._load_model_metadata()

        data = generate_report_data(
            wallet=wallet,
            date=date,
            score_record=score_record,
            feature_vector=feature_vector,
            shap_values=shap_vals,
            benford_metrics=benford_metrics,
            trades=trades,
            model_metadata=model_metadata,
        )

        html = render_html(data)

        if fmt == "pdf":
            return render_pdf(html, output_path)

        with open(output_path, "w") as f:
            f.write(html)
        return output_path

    def _load_score(self, wallet: str, date: str) -> dict:
        import sqlite3
        from config.settings import settings
        try:
            with sqlite3.connect(settings.db_path) as conn:
                conn.row_factory = sqlite3.Row
                row = conn.execute(
                    "SELECT * FROM risk_scores WHERE wallet = ? ORDER BY timestamp DESC LIMIT 1",
                    (wallet,),
                ).fetchone()
                return dict(row) if row else {}
        except (sqlite3.Error, Exception) as e:
            logger.warning("Could not load score for %s: %s", wallet, e)
            return {}

    def _load_benford(self, wallet: str) -> dict:
        try:
            from detection.storage import _connect
            with _connect() as conn:
                conn.row_factory = __import__("sqlite3").Row
                row = conn.execute(
                    "SELECT * FROM risk_scores WHERE wallet = ? ORDER BY timestamp DESC LIMIT 1",
                    (wallet,),
                ).fetchone()
                if row:
                    return {
                        "chi2": 0.0,
                        "mad": 0.0,
                        "flag": bool(row["benford_flag"]) if "benford_flag" in row.keys() else False,
                    }
        except Exception as e:
            logger.warning("Could not load benford metrics for %s: %s", wallet, e)
        return {}

    def _load_trades(self, wallet: str, date: str) -> list:
        return []

    def _load_model_metadata(self) -> dict:
        import json
        from config.settings import settings
        path = os.path.join(settings.model_dir, "training_metadata.json")
        try:
            with open(path) as f:
                return json.load(f)
        except (FileNotFoundError, json.JSONDecodeError):
            return {}
